name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
jobs:
  build :
    name: "Linux Build"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4.1.2
      
      - name: "Set up JDK 8"
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "temurin"
          java-version: "8"
      
      - run: echo "JAVA_8=$JAVA_HOME" >> $GITHUB_ENV
      
      - name: "Set up JDK 17"
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "temurin"
          java-version: "17"
      
      - name: "Build"
        run: "./build.sh clean jar"
      
      - name: "Unit Test"
        run: "./test.sh"
      
      - name: "Upload JAR"
        uses: actions/upload-artifact@v4.3.1
        if: ${{ !github.head_ref }}
        with:
          name: nb-javac-android
          path: ./make/langtools/netbeans/nb-javac/dist/nb-javac-*-android.jar
